### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by TrishGillett** [discardthree/PyQPECgen#2]
Is it actually implemented now?  If not, implement it.

**Comment by jkawamoto** [comment]
I think all modules in qpecgen package use numpy's random module. You can set any seed via [`numpy.random.seed()`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html).

**Comment by TrishGillett** [comment]
Migrated from https://github.com/discardthree/PyQPCC/issues/56
